routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('region', 'RegionController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('person','PersonController');
Route::get('/summary','PersonController@summary');

app/Person.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
    protected $table = 'persons';

    public function getRegion()
    {
        return $this->belongsTo('App\Region','region_id','id');
    }
}

app/Region.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    protected $table = 'regions';

    public function getPerson()
    {
        return $this->hasMany('App\Person','region_id','id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Region;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $summary = Region::with('getPerson')->get();
        //dd($summary);                    
        return view('home',compact('summary'));
    }
}

app/Http/Controllers/PersonController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Person;
use App\Region;


class PersonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $person = Person::all();
        $region = Region::all();
        return view('person.index',compact('person','region'));
    }

    public function summary()
    {
        $summary =  Person::groupBy('region_id')->get();
        $summaryCount = $summary->count();
        dd($summary,$summaryCount);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'income' => 'required',
            'region' => 'required',
            'alamat' => 'required'
        ]);

        $person = new Person();
        $person->name = $request->get('name');
        $person->income = $request->get('income');
        $person->region_id = $request->get('region');
        $person->address = $request->get('alamat');
        $person->save();

        return redirect('/person')->with('message','success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $person = Person::find($id);
        return view('person.show',compact('person'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $person = Person::find($id);
        $region = Region::all();
        return view('person.edit',compact('person','region'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'income' => 'required',
            'region' => 'required',
            'alamat' => 'required'
        ]);


        $person =  Person::find($id);
        $person->name = $request->get('name');
        $person->income = $request->get('income');
        $person->region_id = $request->get('region');
        $person->address = $request->get('alamat');
        $person->save();

        return redirect('/person')->with('message','success');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $person = Person::find($id);
        $person->delete();
        return redirect('/person')->with('message','deleted');
    }
}

app/Http/Controllers/RegionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Region;

class RegionController extends Controller
{
    
    
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $region = Region::all();
        return view('region.index',compact('region'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'region' => 'required',
        ]);

        $region = new Region();
        $region->name = $request->get('region');
        $region->save();
        return redirect('region');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Summary</div>

                <div class="card-body">
                   
                        <div class="card-body">
                               
                                <table class="table table-bordered">
                                    <thead>
                                      <tr>
                                        <th scope="col">No</th>
                                        <th scope="col">Nama Daerah</th>
                                        <th scope="col">Jumlah Penduduk</th>
                                        <th scope="col">Total Pendapatan</th>
                                        <th scop="col">Rata-Rata Pendapatan</th>
                                        <th scope="col">Status</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      @foreach ($summary as $index => $item)
                                          <tr>
                                          <td>{{$index+1}}</td>
                                          <td>{{$item->name}}</td>
                                          <td>{{count($item->getPerson)}}</td>
                                          <td>{{$item->getPerson->sum('income')}}</td>
                                          <td>{{$item->getPerson->avg('income')}}</td>
                                          <td>
                                            @if($item->getPerson->avg('income')>2200000)
                                            <span  style="color:green">hijau</span>
                                            @elseif($item->getPerson->avg('income')>1700000)
                                            <span style="color:yellow">Kuning</span>
                                            @else
                                                <span style="color:red">merah</span>
                                            @endif
                                          </td>
                                          </tr>
                                      @endforeach
                                    </tbody>
                                  </table>
            
            
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{asset('js/jquery.min.js')}}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    @if(Auth::guest())
                    @else
                    <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">Home</a>
                                </li>
        
                                <li class="nav-item">
                                        <a class="nav-link" href="{{ route('region.index') }}">Region</a>
                                </li>
                                <li class="nav-item">
                                        <a class="nav-link" href="{{ route('person.index') }}">Person</a>
                                </li>
                    </ul>
                    @endif

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

           
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
@yield('extrajs')
</html>

resources/views/person/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <br>
                <form action="{{route('person.update',$person->id)}}" method="POST">
                    <input type="hidden" name="_method" value="PUT">
                    @csrf
                        <div class="form-group">
                            <label class="col-md-6 col-sm-6 col-xs-12" for="name">Nama <span class="required"></span>
                            </label>
                            <div class="col-md-6  col-xs-12">
                            <input type="text" name="name" value="{{$person->name}}" required="required" class="form-control  col-xs-4">
                                <ul class="parsley-errors-list filled" style="display:none" id="parsley-id-5"><li class="parsley-required">This value is required.</li></ul>
                            </div>
                        </div>

                         <div class="form-group">
                            <label class="col-md-6 col-sm-6 col-xs-12" for="name">Gaji <span class="required"></span>
                            </label>
                            <div class="col-md-6  col-xs-12">
                                <input type="text" name="income"  value="{{$person->income}}" required="required" class="form-control  col-xs-4">
                                <ul class="parsley-errors-list filled" style="display:none" id="parsley-id-5"><li class="parsley-required">This value is required.</li></ul>
                            </div>
                        </div>


                        <div class="form-group">
                                <label class="col-md-6 col-sm-6 col-xs-12" for="name">Region <span class="required"></span>
                                </label>
                                <div class="col-md-6  col-xs-12">
                                    <select  name="region" required="required" class="form-control  col-xs-4">
                                    @foreach ($region as $item)
                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                    @endforeach  
                                    </select>
                                    <ul class="parsley-errors-list filled" style="display:none" id="parsley-id-5"><li class="parsley-required">This value is required.</li></ul>
                                </div>
                        </div>

                        <div class="form-group">
                                <label class="col-md-6 col-sm-6 col-xs-12" for="name">alamat <span class="required"></span>
                                </label>
                                <div class="col-md-6  col-xs-12">
                                    <textarea name="alamat"  required="required" class="form-control  col-xs-4"> {{$person->address}}</textarea>
                                    <ul class="parsley-errors-list filled" style="display:none" id="parsley-id-5"><li class="parsley-required">This value is required.</li></ul>
                                </div>
                            </div>

                        <div class="form-group">    
                            <div class="col-md-6  col-xs-12">
                                 <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                           
                        </div>    
                    </form>
                   

                </div>
            </div>
        </div>
</div>
    
@endsection

resources/views/person/index.blade.php
@extends('layouts.app')
@section('content')


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Person</div>

                <div class="card-body">
                    <button data-toggle="modal" data-target="#addPerson"  class="btn btn-success" style="float:right">Tambah Person</button>
                    <div class="clearfix"></div>
                    <br>
                    <input class="form-control" id="myInput" type="text" placeholder="Search..">
                    <br>
                    <table id="myTable" class="table table-bordered">
                        <thead>
                          <tr>
                            <th scope="col">No</th>
                            <th scope="col">Nama Penduduk</th>
                            <th scope="col">Gaji</th>
                            <th scope="col">Daerah</th>
                            <th scop="col">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach ($person as $index => $item)
                            <tr>
                            <td>{{$index +1}} </td>
                            <td>{{$item->name}}</td>
                            <td>{{$item->income}}</td>
                            <td>{{$item->getRegion->name}}</td>
                            <td align="center">
                                <a href="{{route('person.edit',$item->id)}}" class="btn-sm btn-success">Ubah</a>
                                <a href="{{route('person.show',$item->id)}}" class="btn-sm btn-primary">Lihat</a>
                                <form action="{{route('person.destroy',$item->id)}}" method="post">
                                  {{ method_field('delete')}}
                                  @csrf
                                <button href="{{route('person.destroy',$item->id)}}" class="btn-sm btn-danger">Hapus</button>
                                </form>  
                            </td>
                          @endforeach
                        </tbody>
                      </table>


                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade bs-example-modal-lg" id="addPerson" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
    <form id="demo-form1" method="post" action="{{route('person.store')}}" data-parsley-validate="" class="form-horizontal form-label-left" novalidate="">
            @csrf
            <div class="modal-content">
                <div class="modal-header">
                  
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-md-6 col-sm-6 col-xs-12" for="name">Nama <span class="required"></span>
                        </label>
                        <div class="col-md-6  col-xs-12">
                            <input type="text" name="name" required="required" class="form-control  col-xs-4">
                            <ul class="parsley-errors-list filled" style="display:none" id="parsley-id-5"><li class="parsley-required">This value is required.</li></ul>
                        </div>
                    </div>

                    <div class="form-group">
                      <label class="col-md-6 col-sm-6 col-xs-12" for="name">Gaji <span class="required"></span>
                      </label>
                      <div class="col-md-6  col-xs-12">
                          <input type="text" name="income" required="required" class="form-control  col-xs-4">
                          <ul class="parsley-errors-list filled" style="display:none" id="parsley-id-5"><li class="parsley-required">This value is required.</li></ul>
                      </div>
                  </div>

                  <div class="form-group">
                      <label class="col-md-6 col-sm-6 col-xs-12" for="name">Region <span class="required"></span>
                      </label>
                      <div class="col-md-6  col-xs-12">
                          <select  name="region" required="required" class="form-control  col-xs-4">
                          @foreach ($region as $item)
                          <option value="{{$item->id}}">{{$item->name}}</option>
                          @endforeach  
                          </select>
                          <ul class="parsley-errors-list filled" style="display:none" id="parsley-id-5"><li class="parsley-required">This value is required.</li></ul>
                      </div>
                  </div>

                  <div class="form-group">
                    <label class="col-md-6 col-sm-6 col-xs-12" for="name">alamat <span class="required"></span>
                    </label>
                    <div class="col-md-6  col-xs-12">
                        <textarea name="alamat" required="required" class="form-control  col-xs-4">
                        </textarea>
                        <ul class="parsley-errors-list filled" style="display:none" id="parsley-id-5"><li class="parsley-required">This value is required.</li></ul>
                    </div>
                </div>
                  
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>


    
@endsection
@section('extrajs')
<script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
              var value = $(this).val().toLowerCase();
              $("#myTable tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
              });
            });
          });
</script>    
@endsection

resources/views/person/show.blade.php
@extends('layouts.app')
@section('content')


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
            <div class="card-header">{{$person->name}}</div>

                <div class="card-body">
                   
                    <div class="title m-b-md">
                        Nama : {{$person->name}}          
                    </div>

                    <div class="title m-b-md">
                        Income : Rp.{{$person->income}}          
                    </div>

                    <div class="title m-b-md">
                         Address : {{$person->address}}          
                    </div>

                    <div class="title m-b-md">
                        region : {{$person->getRegion->name}}          
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>





    
@endsection

resources/views/region/index.blade.php
@extends('layouts.app')
@section('content')


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Region</div>

                <div class="card-body">
                    <button data-toggle="modal" data-target="#addRegion"  class="btn btn-success" style="float:right">Tambah Region</button>
                    <div class="clearfix"></div>
                    <br>
                    <input class="form-control" id="myInput" type="text" placeholder="Search..">
                    <br>

                    <table id="myTable" class="table table-bordered">
                        <thead>
                          <tr>
                            <th scope="col">No</th>
                            <th scope="col">Region</th>
                            <th scope="col">Created At</th>
                            <th scope="col">Updated At</th>
                           
                          </tr>
                        </thead>
                        <tbody>
                          @foreach ($region as $index => $item)
                            <tr>
                            <td>{{$index +1}} </td>
                            <td>{{$item->name}}</td>
                            <td>{{$item->created_at}}</td>
                            <td>{{$item->updated_at}}</td>
                         
                          @endforeach
                        </tbody>
                      </table>


                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade bs-example-modal-lg" id="addRegion" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
    <form id="demo-form1" method="post" action="{{route('region.store')}}" data-parsley-validate="" class="form-horizontal form-label-left" novalidate="">
            @csrf
            <div class="modal-content">
                <div class="modal-header">
                  
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-md-6 col-sm-6 col-xs-12" for="name">Nama Region<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" name="region" required="required" class="form-control col-md-7 col-xs-12">
                            <ul class="parsley-errors-list filled" style="display:none" id="parsley-id-5"><li class="parsley-required">This value is required.</li></ul>
                        </div>
                    </div>
                  
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>


    
@endsection
@section('extrajs')
<script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
              var value = $(this).val().toLowerCase();
              $("#myTable tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
              });
            });
          });
</script>    
@endsection